// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.kharcha_core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_kharcha_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_kharcha_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Only `lower` is valid — zero-copy byte buffers only flow foreign -> Rust,
// and only in argument position. `lift`, `read`, `write`, and
// `allocationSize` have no sound implementation here and all panic at
// runtime. The `FfiConverter` interface is implemented so that the
// compiler enforces the full method set (rather than relying on eyeball).
//
// The provided `ByteBuffer` MUST be direct — only direct buffers have a
// stable native address that JNA can expose via `getDirectBufferPointer`.
// The returned `ForeignBytes.ByValue` is only valid for the duration of
// the FFI call; the Rust side treats it as a borrow.
internal object FfiConverterByRefBytes : FfiConverter<java.nio.ByteBuffer, ForeignBytes.ByValue> {
    override fun lower(value: java.nio.ByteBuffer): ForeignBytes.ByValue {
        require(value.isDirect) { "UniFFI zero-copy &[u8] requires a direct ByteBuffer. Use ByteBuffer.allocateDirect()." }
        val remaining = value.remaining()
        val fb = ForeignBytes.ByValue()
        fb.len = remaining
        // Zero-length direct buffers: skip getDirectBufferPointer (platform-variable behavior)
        // and pass null. The Rust side treats (null, 0) as &[].
        fb.data = if (remaining == 0) null else com.sun.jna.Native.getDirectBufferPointer(value)
        return fb
    }

    override fun lift(value: ForeignBytes.ByValue): java.nio.ByteBuffer =
        error("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    override fun read(buf: java.nio.ByteBuffer): java.nio.ByteBuffer =
        error("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun write(value: java.nio.ByteBuffer, buf: java.nio.ByteBuffer): Unit =
        error("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun allocationSize(value: java.nio.ByteBuffer): ULong =
        error("ByRef bytes have no RustBuffer allocation size: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "kharcha_core"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "kharcha_core"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_kharcha_core_checksum_func_apply_filter(
    ): Int
    external fun uniffi_kharcha_core_checksum_func_categorize_merchant(
    ): Int
    external fun uniffi_kharcha_core_checksum_func_check_capture(
    ): Int
    external fun uniffi_kharcha_core_checksum_func_encode_inbox_line(
    ): Int
    external fun uniffi_kharcha_core_checksum_func_is_spam(
    ): Int
    external fun uniffi_kharcha_core_checksum_func_normalize_merchant_text(
    ): Int
    external fun uniffi_kharcha_core_checksum_func_parse_amount(
    ): Int
    external fun uniffi_kharcha_core_checksum_func_parse_capture(
    ): Int
    external fun uniffi_kharcha_core_checksum_func_parse_captures(
    ): Int
    external fun uniffi_kharcha_core_checksum_func_split_bill(
    ): Int
    external fun ffi_kharcha_core_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "kharcha_core"))
        
    }
    external fun uniffi_kharcha_core_fn_func_apply_filter(`f`: RustBuffer.ByValue,`rows`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_kharcha_core_fn_func_categorize_merchant(`merchant`: RustBuffer.ByValue,`rules`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_kharcha_core_fn_func_check_capture(`candidateRef`: RustBuffer.ByValue,`amountPaise`: Long,`isIncome`: Byte,`txnMs`: Long,`candidateHash`: RustBuffer.ByValue,`existing`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_kharcha_core_fn_func_encode_inbox_line(`package`: RustBuffer.ByValue,`text`: RustBuffer.ByValue,`seenAt`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_kharcha_core_fn_func_is_spam(`text`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_kharcha_core_fn_func_normalize_merchant_text(`raw`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_kharcha_core_fn_func_parse_amount(`text`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_kharcha_core_fn_func_parse_capture(`smsBody`: RustBuffer.ByValue,`sender`: RustBuffer.ByValue,`timestampMs`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_kharcha_core_fn_func_parse_captures(`items`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_kharcha_core_fn_func_split_bill(`totalPaise`: Long,`count`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_kharcha_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_kharcha_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_kharcha_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_kharcha_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_kharcha_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_kharcha_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_kharcha_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_kharcha_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_kharcha_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_kharcha_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_kharcha_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_kharcha_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_kharcha_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_kharcha_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_kharcha_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_kharcha_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_kharcha_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_kharcha_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if ((lib.uniffi_kharcha_core_checksum_func_apply_filter() and 0xFFFF) != 30064) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_kharcha_core_checksum_func_categorize_merchant() and 0xFFFF) != 30557) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_kharcha_core_checksum_func_check_capture() and 0xFFFF) != 6990) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_kharcha_core_checksum_func_encode_inbox_line() and 0xFFFF) != 49241) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_kharcha_core_checksum_func_is_spam() and 0xFFFF) != 6271) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_kharcha_core_checksum_func_normalize_merchant_text() and 0xFFFF) != 42102) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_kharcha_core_checksum_func_parse_amount() and 0xFFFF) != 46024) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_kharcha_core_checksum_func_parse_capture() and 0xFFFF) != 56026) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_kharcha_core_checksum_func_parse_captures() and 0xFFFF) != 18695) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_kharcha_core_checksum_func_split_bill() and 0xFFFF) != 15244) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



/**
 * One batch-drain item (uniffi has no tuples).
 */
data class CaptureInput (
    var `body`: kotlin.String
    , 
    var `sender`: kotlin.String
    , 
    var `timestampMs`: kotlin.Long
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCaptureInput: FfiConverterRustBuffer<CaptureInput> {
    override fun read(buf: ByteBuffer): CaptureInput {
        return CaptureInput(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
        )
    }

    override fun allocationSize(value: CaptureInput) = (
            FfiConverterString.allocationSize(value.`body`) +
            FfiConverterString.allocationSize(value.`sender`) +
            FfiConverterLong.allocationSize(value.`timestampMs`)
    )

    override fun write(value: CaptureInput, buf: ByteBuffer) {
            FfiConverterString.write(value.`body`, buf)
            FfiConverterString.write(value.`sender`, buf)
            FfiConverterLong.write(value.`timestampMs`, buf)
    }
}



/**
 * A stored transaction row, as far as dedupe cares.
 */
data class ExistingRow (
    var `upiRef`: kotlin.String?
    , 
    var `amountPaise`: kotlin.Long
    , 
    var `isIncome`: kotlin.Boolean
    , 
    /**
     * Epoch millis.
     */
    var `txnMs`: kotlin.Long
    , 
    var `isDeleted`: kotlin.Boolean
    , 
    /**
     * `engine::content_hash` at insert time. Legacy rows carry None —
     * the hash signal skips them (ref + window still apply).
     */
    var `contentHash`: kotlin.ULong?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeExistingRow: FfiConverterRustBuffer<ExistingRow> {
    override fun read(buf: ByteBuffer): ExistingRow {
        return ExistingRow(
            FfiConverterOptionalString.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalULong.read(buf),
        )
    }

    override fun allocationSize(value: ExistingRow) = (
            FfiConverterOptionalString.allocationSize(value.`upiRef`) +
            FfiConverterLong.allocationSize(value.`amountPaise`) +
            FfiConverterBoolean.allocationSize(value.`isIncome`) +
            FfiConverterLong.allocationSize(value.`txnMs`) +
            FfiConverterBoolean.allocationSize(value.`isDeleted`) +
            FfiConverterOptionalULong.allocationSize(value.`contentHash`)
    )

    override fun write(value: ExistingRow, buf: ByteBuffer) {
            FfiConverterOptionalString.write(value.`upiRef`, buf)
            FfiConverterLong.write(value.`amountPaise`, buf)
            FfiConverterBoolean.write(value.`isIncome`, buf)
            FfiConverterLong.write(value.`txnMs`, buf)
            FfiConverterBoolean.write(value.`isDeleted`, buf)
            FfiConverterOptionalULong.write(value.`contentHash`, buf)
    }
}



/**
 * A UPI/bank payment parsed from a notification's text.
 */
data class ParsedPayment (
    /**
     * Integer paise (Dart stores a 2dp double; same value, exact).
     */
    var `amountPaise`: kotlin.Long
    , 
    var `merchant`: kotlin.String
    , 
    /**
     * True when money came IN (received/credited). False for spending.
     */
    var `isIncome`: kotlin.Boolean
    , 
    var `upiRef`: kotlin.String?
    , 
    /**
     * True bank balance extracted from the message, paise.
     */
    var `balancePaise`: kotlin.Long?
    , 
    var `accountMask`: kotlin.String?
    , 
    var `bankName`: kotlin.String?
    , 
    var `needsReview`: kotlin.Boolean
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeParsedPayment: FfiConverterRustBuffer<ParsedPayment> {
    override fun read(buf: ByteBuffer): ParsedPayment {
        return ParsedPayment(
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalLong.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: ParsedPayment) = (
            FfiConverterLong.allocationSize(value.`amountPaise`) +
            FfiConverterString.allocationSize(value.`merchant`) +
            FfiConverterBoolean.allocationSize(value.`isIncome`) +
            FfiConverterOptionalString.allocationSize(value.`upiRef`) +
            FfiConverterOptionalLong.allocationSize(value.`balancePaise`) +
            FfiConverterOptionalString.allocationSize(value.`accountMask`) +
            FfiConverterOptionalString.allocationSize(value.`bankName`) +
            FfiConverterBoolean.allocationSize(value.`needsReview`)
    )

    override fun write(value: ParsedPayment, buf: ByteBuffer) {
            FfiConverterLong.write(value.`amountPaise`, buf)
            FfiConverterString.write(value.`merchant`, buf)
            FfiConverterBoolean.write(value.`isIncome`, buf)
            FfiConverterOptionalString.write(value.`upiRef`, buf)
            FfiConverterOptionalLong.write(value.`balancePaise`, buf)
            FfiConverterOptionalString.write(value.`accountMask`, buf)
            FfiConverterOptionalString.write(value.`bankName`, buf)
            FfiConverterBoolean.write(value.`needsReview`, buf)
    }
}



/**
 * A parsed capture with provenance. Mirrors pennywise `ParsedTransaction`:
 * sender + timestamp travel WITH the payment, not in a sidecar inbox line.
 */
data class ParsedTransaction (
    var `payment`: ParsedPayment
    , 
    /**
     * Sender ID, trimmed + uppercased (sender IDs are case-noisy).
     */
    var `sender`: kotlin.String
    , 
    /**
     * Capture timestamp, epoch millis (carrier or device clock).
     */
    var `timestampMs`: kotlin.Long
    , 
    /**
     * Deterministic content key over sender|amount|direction|merchant|ref.
     * FNV-1a64, stable across restarts (unlike SipHash) — safe as a dedupe
     * key. This is what kharcha's upiRef+window and pennywise's md5(body)
     * both wanted: exact redelivery across channels/times dies here even
     * with no ref and outside the time window.
     */
    var `contentHash`: kotlin.ULong
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeParsedTransaction: FfiConverterRustBuffer<ParsedTransaction> {
    override fun read(buf: ByteBuffer): ParsedTransaction {
        return ParsedTransaction(
            FfiConverterTypeParsedPayment.read(buf),
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: ParsedTransaction) = (
            FfiConverterTypeParsedPayment.allocationSize(value.`payment`) +
            FfiConverterString.allocationSize(value.`sender`) +
            FfiConverterLong.allocationSize(value.`timestampMs`) +
            FfiConverterULong.allocationSize(value.`contentHash`)
    )

    override fun write(value: ParsedTransaction, buf: ByteBuffer) {
            FfiConverterTypeParsedPayment.write(value.`payment`, buf)
            FfiConverterString.write(value.`sender`, buf)
            FfiConverterLong.write(value.`timestampMs`, buf)
            FfiConverterULong.write(value.`contentHash`, buf)
    }
}



/**
 * Merchant normalization + rule-based categorization. Rule-based only — no AI.
 * Port of `lib/core/categorizer.dart`.
 *
 * Match is a word-boundary substring on normalized strings, which doubles as
 * the fuzzy match: "Zomato", "ZOMATO-UB", "zomato order" all hit "zomato",
 * but never inside "buzzomatic".
 * Minimal rule row (callers map their storage rows onto this).
 */
data class Rule (
    var `pattern`: kotlin.String
    , 
    /**
     * "learned" beats "builtin".
     */
    var `ruleType`: kotlin.String
    , 
    var `categoryId`: kotlin.Long?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRule: FfiConverterRustBuffer<Rule> {
    override fun read(buf: ByteBuffer): Rule {
        return Rule(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalLong.read(buf),
        )
    }

    override fun allocationSize(value: Rule) = (
            FfiConverterString.allocationSize(value.`pattern`) +
            FfiConverterString.allocationSize(value.`ruleType`) +
            FfiConverterOptionalLong.allocationSize(value.`categoryId`)
    )

    override fun write(value: Rule, buf: ByteBuffer) {
            FfiConverterString.write(value.`pattern`, buf)
            FfiConverterString.write(value.`ruleType`, buf)
            FfiConverterOptionalLong.write(value.`categoryId`, buf)
    }
}



data class TransactionFilter (
    /**
     * Free-text, case-insensitive over merchant + note (+ upi ref + amount).
     */
    var `query`: kotlin.String
    , 
    var `categoryId`: kotlin.Long?
    , 
    /**
     * Exact merchant name (None = all).
     */
    var `merchant`: kotlin.String?
    , 
    /**
     * cash | upi | card | wallet (None = all).
     */
    var `paymentMethod`: kotlin.String?
    , 
    var `isIncome`: kotlin.Boolean?
    , 
    /**
     * Earliest txn, inclusive (None = unbounded).
     */
    var `fromMs`: kotlin.Long?
    , 
    /**
     * Latest txn, inclusive (None = unbounded).
     */
    var `toMs`: kotlin.Long?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTransactionFilter: FfiConverterRustBuffer<TransactionFilter> {
    override fun read(buf: ByteBuffer): TransactionFilter {
        return TransactionFilter(
            FfiConverterString.read(buf),
            FfiConverterOptionalLong.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalBoolean.read(buf),
            FfiConverterOptionalLong.read(buf),
            FfiConverterOptionalLong.read(buf),
        )
    }

    override fun allocationSize(value: TransactionFilter) = (
            FfiConverterString.allocationSize(value.`query`) +
            FfiConverterOptionalLong.allocationSize(value.`categoryId`) +
            FfiConverterOptionalString.allocationSize(value.`merchant`) +
            FfiConverterOptionalString.allocationSize(value.`paymentMethod`) +
            FfiConverterOptionalBoolean.allocationSize(value.`isIncome`) +
            FfiConverterOptionalLong.allocationSize(value.`fromMs`) +
            FfiConverterOptionalLong.allocationSize(value.`toMs`)
    )

    override fun write(value: TransactionFilter, buf: ByteBuffer) {
            FfiConverterString.write(value.`query`, buf)
            FfiConverterOptionalLong.write(value.`categoryId`, buf)
            FfiConverterOptionalString.write(value.`merchant`, buf)
            FfiConverterOptionalString.write(value.`paymentMethod`, buf)
            FfiConverterOptionalBoolean.write(value.`isIncome`, buf)
            FfiConverterOptionalLong.write(value.`fromMs`, buf)
            FfiConverterOptionalLong.write(value.`toMs`, buf)
    }
}



/**
 * Client-side filter for the transactions list. Immutable.
 * Port of `lib/core/transaction_filter.dart`. Pure: no DB, no clock.
 * Dates are epoch millis — comparisons only, so TZ never enters this file
 * (Dart compares `DateTime`s; the corpus fixes them to UTC millis).
 * Minimal transaction row (callers map their storage rows onto this).
 */
data class TxRow (
    var `id`: kotlin.Long
    , 
    var `amountPaise`: kotlin.Long
    , 
    var `merchant`: kotlin.String
    , 
    var `categoryId`: kotlin.Long?
    , 
    var `paymentMethod`: kotlin.String
    , 
    var `isIncome`: kotlin.Boolean
    , 
    /**
     * Epoch millis, inclusive bounds.
     */
    var `txnMs`: kotlin.Long
    , 
    var `note`: kotlin.String?
    , 
    var `upiRef`: kotlin.String?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTxRow: FfiConverterRustBuffer<TxRow> {
    override fun read(buf: ByteBuffer): TxRow {
        return TxRow(
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: TxRow) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterLong.allocationSize(value.`amountPaise`) +
            FfiConverterString.allocationSize(value.`merchant`) +
            FfiConverterOptionalLong.allocationSize(value.`categoryId`) +
            FfiConverterString.allocationSize(value.`paymentMethod`) +
            FfiConverterBoolean.allocationSize(value.`isIncome`) +
            FfiConverterLong.allocationSize(value.`txnMs`) +
            FfiConverterOptionalString.allocationSize(value.`note`) +
            FfiConverterOptionalString.allocationSize(value.`upiRef`)
    )

    override fun write(value: TxRow, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterLong.write(value.`amountPaise`, buf)
            FfiConverterString.write(value.`merchant`, buf)
            FfiConverterOptionalLong.write(value.`categoryId`, buf)
            FfiConverterString.write(value.`paymentMethod`, buf)
            FfiConverterBoolean.write(value.`isIncome`, buf)
            FfiConverterLong.write(value.`txnMs`, buf)
            FfiConverterOptionalString.write(value.`note`, buf)
            FfiConverterOptionalString.write(value.`upiRef`, buf)
    }
}



/**
 * Caller applies the storage side-effect (insert row / write ref onto row id).
 */
sealed class CaptureDecision {
    
    object Insert : CaptureDecision()
    
    
    data class Skip(
        /**
         * Write the candidate ref onto the matched row (it had none).
         */
        val `backfillRef`: kotlin.Boolean) : CaptureDecision()
        
    {
        

        companion object
    }
    

    

    
    


    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCaptureDecision : FfiConverterRustBuffer<CaptureDecision>{
    override fun read(buf: ByteBuffer): CaptureDecision {
        return when(buf.getInt()) {
            1 -> CaptureDecision.Insert
            2 -> CaptureDecision.Skip(
                FfiConverterBoolean.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: CaptureDecision): ULong = when(value) {
        is CaptureDecision.Insert -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
            )
        }
        is CaptureDecision.Skip -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterBoolean.allocationSize(value.`backfillRef`)
            )
        }
    }

    override fun write(value: CaptureDecision, buf: ByteBuffer) {
        when(value) {
            is CaptureDecision.Insert -> {
                buf.putInt(1)
                Unit
            }
            is CaptureDecision.Skip -> {
                buf.putInt(2)
                FfiConverterBoolean.write(value.`backfillRef`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalULong: FfiConverterRustBuffer<kotlin.ULong?> {
    override fun read(buf: ByteBuffer): kotlin.ULong? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterULong.read(buf)
    }

    override fun allocationSize(value: kotlin.ULong?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterULong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.ULong?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterULong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalLong: FfiConverterRustBuffer<kotlin.Long?> {
    override fun read(buf: ByteBuffer): kotlin.Long? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterLong.read(buf)
    }

    override fun allocationSize(value: kotlin.Long?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterLong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Long?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterLong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalBoolean: FfiConverterRustBuffer<kotlin.Boolean?> {
    override fun read(buf: ByteBuffer): kotlin.Boolean? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterBoolean.read(buf)
    }

    override fun allocationSize(value: kotlin.Boolean?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterBoolean.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Boolean?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterBoolean.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeParsedTransaction: FfiConverterRustBuffer<ParsedTransaction?> {
    override fun read(buf: ByteBuffer): ParsedTransaction? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeParsedTransaction.read(buf)
    }

    override fun allocationSize(value: ParsedTransaction?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeParsedTransaction.allocationSize(value)
        }
    }

    override fun write(value: ParsedTransaction?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeParsedTransaction.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeRule: FfiConverterRustBuffer<Rule?> {
    override fun read(buf: ByteBuffer): Rule? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeRule.read(buf)
    }

    override fun allocationSize(value: Rule?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeRule.allocationSize(value)
        }
    }

    override fun write(value: Rule?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeRule.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceLong: FfiConverterRustBuffer<List<kotlin.Long>> {
    override fun read(buf: ByteBuffer): List<kotlin.Long> {
        val len = buf.getInt()
        return List<kotlin.Long>(len) {
            FfiConverterLong.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.Long>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterLong.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.Long>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterLong.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeCaptureInput: FfiConverterRustBuffer<List<CaptureInput>> {
    override fun read(buf: ByteBuffer): List<CaptureInput> {
        val len = buf.getInt()
        return List<CaptureInput>(len) {
            FfiConverterTypeCaptureInput.read(buf)
        }
    }

    override fun allocationSize(value: List<CaptureInput>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeCaptureInput.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<CaptureInput>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeCaptureInput.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeExistingRow: FfiConverterRustBuffer<List<ExistingRow>> {
    override fun read(buf: ByteBuffer): List<ExistingRow> {
        val len = buf.getInt()
        return List<ExistingRow>(len) {
            FfiConverterTypeExistingRow.read(buf)
        }
    }

    override fun allocationSize(value: List<ExistingRow>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeExistingRow.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ExistingRow>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeExistingRow.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeRule: FfiConverterRustBuffer<List<Rule>> {
    override fun read(buf: ByteBuffer): List<Rule> {
        val len = buf.getInt()
        return List<Rule>(len) {
            FfiConverterTypeRule.read(buf)
        }
    }

    override fun allocationSize(value: List<Rule>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeRule.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<Rule>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeRule.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeTxRow: FfiConverterRustBuffer<List<TxRow>> {
    override fun read(buf: ByteBuffer): List<TxRow> {
        val len = buf.getInt()
        return List<TxRow>(len) {
            FfiConverterTypeTxRow.read(buf)
        }
    }

    override fun allocationSize(value: List<TxRow>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeTxRow.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<TxRow>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeTxRow.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceOptionalTypeParsedTransaction: FfiConverterRustBuffer<List<ParsedTransaction?>> {
    override fun read(buf: ByteBuffer): List<ParsedTransaction?> {
        val len = buf.getInt()
        return List<ParsedTransaction?>(len) {
            FfiConverterOptionalTypeParsedTransaction.read(buf)
        }
    }

    override fun allocationSize(value: List<ParsedTransaction?>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterOptionalTypeParsedTransaction.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ParsedTransaction?>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterOptionalTypeParsedTransaction.write(it, buf)
        }
    }
} fun `applyFilter`(`f`: TransactionFilter, `rows`: List<TxRow>): List<TxRow> {
            return FfiConverterSequenceTypeTxRow.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_kharcha_core_fn_func_apply_filter(
    
        
        FfiConverterTypeTransactionFilter.lower(`f`),
        FfiConverterSequenceTypeTxRow.lower(`rows`),_status)
}
    )
    }
    
 fun `categorizeMerchant`(`merchant`: kotlin.String, `rules`: List<Rule>): Rule? {
            return FfiConverterOptionalTypeRule.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_kharcha_core_fn_func_categorize_merchant(
    
        
        FfiConverterString.lower(`merchant`),
        FfiConverterSequenceTypeRule.lower(`rules`),_status)
}
    )
    }
    
 fun `checkCapture`(`candidateRef`: kotlin.String?, `amountPaise`: kotlin.Long, `isIncome`: kotlin.Boolean, `txnMs`: kotlin.Long, `candidateHash`: kotlin.ULong?, `existing`: List<ExistingRow>): CaptureDecision {
            return FfiConverterTypeCaptureDecision.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_kharcha_core_fn_func_check_capture(
    
        
        FfiConverterOptionalString.lower(`candidateRef`),
        FfiConverterLong.lower(`amountPaise`),
        FfiConverterBoolean.lower(`isIncome`),
        FfiConverterLong.lower(`txnMs`),
        FfiConverterOptionalULong.lower(`candidateHash`),
        FfiConverterSequenceTypeExistingRow.lower(`existing`),_status)
}
    )
    }
    
 fun `encodeInboxLine`(`package`: kotlin.String, `text`: kotlin.String, `seenAt`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_kharcha_core_fn_func_encode_inbox_line(
    
        
        FfiConverterString.lower(`package`),
        FfiConverterString.lower(`text`),
        FfiConverterString.lower(`seenAt`),_status)
}
    )
    }
    
 fun `isSpam`(`text`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_kharcha_core_fn_func_is_spam(
    
        
        FfiConverterString.lower(`text`),_status)
}
    )
    }
    
 fun `normalizeMerchantText`(`raw`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_kharcha_core_fn_func_normalize_merchant_text(
    
        
        FfiConverterString.lower(`raw`),_status)
}
    )
    }
    
 fun `parseAmount`(`text`: kotlin.String?): kotlin.Long? {
            return FfiConverterOptionalLong.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_kharcha_core_fn_func_parse_amount(
    
        
        FfiConverterOptionalString.lower(`text`),_status)
}
    )
    }
    
 fun `parseCapture`(`smsBody`: kotlin.String, `sender`: kotlin.String, `timestampMs`: kotlin.Long): ParsedTransaction? {
            return FfiConverterOptionalTypeParsedTransaction.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_kharcha_core_fn_func_parse_capture(
    
        
        FfiConverterString.lower(`smsBody`),
        FfiConverterString.lower(`sender`),
        FfiConverterLong.lower(`timestampMs`),_status)
}
    )
    }
    
 fun `parseCaptures`(`items`: List<CaptureInput>): List<ParsedTransaction?> {
            return FfiConverterSequenceOptionalTypeParsedTransaction.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_kharcha_core_fn_func_parse_captures(
    
        
        FfiConverterSequenceTypeCaptureInput.lower(`items`),_status)
}
    )
    }
    
 fun `splitBill`(`totalPaise`: kotlin.Long, `count`: kotlin.ULong): List<kotlin.Long> {
            return FfiConverterSequenceLong.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_kharcha_core_fn_func_split_bill(
    
        
        FfiConverterLong.lower(`totalPaise`),
        FfiConverterULong.lower(`count`),_status)
}
    )
    }
    


